const permissionDescriptions = {
  "user:view:any": "View all users.",
  "user:manage:any": "Create, update, and deactivate any user.",
  "user:view:team": "View users in the current administrator's team.",
  "user:manage:team": "Manage employees in the current administrator's team.",
  "role:manage": "Manage roles and role assignments.",
  "permission:manage": "Manage permissions and role grants.",
  "settings:manage": "Manage system settings.",
  "audit:view": "View system audit logs.",
  "project:create": "Create projects.",
  "project:view:any": "View all projects.",
  "project:view:own": "View owned projects.",
  "task:create": "Create tasks.",
  "task:assign": "Assign tasks to eligible users.",
  "task:view:any": "View all tasks.",
  "task:view:own": "View tasks within the user's scope.",
  "task:update:any": "Update any task.",
  "task:update:own": "Update tasks within the user's scope.",
  "ticket:create": "Create tickets.",
  "ticket:assign": "Assign tickets to eligible users.",
  "ticket:view:any": "View all tickets.",
  "ticket:view:own": "View tickets within the user's scope.",
  "ticket:update:any": "Update any ticket.",
  "ticket:update:own": "Update tickets within the user's scope.",
  "ticket:comment:create:own": "Comment on tickets within the user's scope.",
  "report:view:any": "View all reports.",
  "report:view:own": "View reports within the user's scope.",
  "attachment:create:own": "Attach files to tasks within the user's scope.",
};

const rolePermissions = {
  SUPER_ADMIN: Object.keys(permissionDescriptions),
  ADMIN: [
    "user:view:team",
    "user:manage:team",
    "project:create",
    "project:view:own",
    "task:create",
    "task:assign",
    "task:view:own",
    "task:update:own",
    "ticket:create",
    "ticket:assign",
    "ticket:view:own",
    "ticket:update:own",
    "ticket:comment:create:own",
    "report:view:own",
    "attachment:create:own",
  ],
  MANAGER: [
    "project:view:own",
    "task:view:own",
    "task:update:own",
    "ticket:view:own",
    "ticket:comment:create:own",
    "report:view:own",
    "attachment:create:own",
  ],
  EMPLOYEE: [
    "task:view:own",
    "task:update:own",
    "ticket:create",
    "ticket:view:own",
    "ticket:comment:create:own",
    "attachment:create:own",
  ],
};

module.exports = { permissionDescriptions, rolePermissions };
